name: "Build .NET"
description: "Build .NET"
inputs:
  version:
    description: "The version of the build"
    required: true
  configuration:
    description: "The Build Configuration"
    required: true
    default: "Release"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: src
      shell: bash
      run: dotnet restore
    - name: Build
      working-directory: src
      shell: bash
      run: dotnet build --configuration ${{ inputs.configuration }} --no-restore
